name: bag_py3d7_c
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - astroid=2.11.7=py37h06a4308_0
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - dill=0.3.6=py37h06a4308_0
  - expat=2.4.4=h295c915_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fmt=8.0.1=h4bd325d_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.11.0=h70c0345_0
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=he6710b0_3
  - isort=5.9.3=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - lazy-object-proxy=1.6.0=py37h27cfd23_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libuuid=1.0.3=h7f8727e_2
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.12=h03d6c58_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1k=h7f98852_0
  - pcre=8.45=h295c915_0
  - pip=21.2.2=py37h06a4308_0
  - platformdirs=2.5.2=py37h06a4308_0
  - pylint=2.14.5=py37h06a4308_0
  - python=3.7.7=hcff3b4d_5
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py37h06a4308_0
  - spdlog=1.9.1=h4bd325d_0
  - sqlite=3.37.2=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - tomli=2.0.1=py37h06a4308_0
  - tomlkit=0.11.1=py37h06a4308_0
  - typed-ast=1.4.3=py37h7f8727e_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.13.3=py37h7f8727e_2
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
      - apipkg==1.5
      - appdirs==1.4.3
      - argparse==1.4.0
      - arrow==1.2.2
      - attrs==19.3.0
      - backcall==0.1.0
      - cycler==0.10.0
      - decorator==4.4.2
      - distlib==0.3.0
      - docopt==0.6.2
      - execnet==1.7.1
      - filelock==3.0.12
      - h5py==2.10.0
      - importlib-metadata==1.6.0
      - inform==1.26.0
      - ipython==7.13.0
      - ipython-genutils==0.2.0
      - jedi==0.16.0
      - jinja2==2.11.1
      - kiwisolver==1.2.0
      - libpsf==0.1.3
      - markupsafe==1.1.1
      - matplotlib==3.2.1
      - more-itertools==8.2.0
      - networkx==2.4
      - numpy==1.18.2
      - packaging==20.3
      - pandocfilters==1.4.2
      - parso==0.6.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pluggy==0.13.1
      - ply==3.4
      - prompt-toolkit==3.0.5
      - psf-utils==1.5.0
      - ptyprocess==0.6.0
      - py==1.8.1
      - pygments==2.6.1
      - pyparsing==2.4.6
      - pyqt5==5.14.0
      - pyqt5-sip==12.7.1
      - pytest==5.4.1
      - pytest-forked==1.1.3
      - pytest-xdist==1.31.0
      - python-dateutil==2.8.1
      - pyzmq==19.0.0
      - quantiphy==2.17.0
      - ruamel-yaml==0.16.10
      - ruamel-yaml-clib==0.2.0
      - scipy==1.4.1
      - six==1.14.0
      - sortedcontainers==2.1.0
      - traitlets==4.3.3
      - typing-extensions==4.1.1
      - virtualenv==20.0.15
      - wcwidth==0.1.9
      - zipp==3.1.0
      - zmq==0.0.0
prefix: bag_3d7_c
